### ISSUE TITLE
Test run failing with new offences from RuboCop 0.49.1

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-cookbooks#863]
The Travis run for #854 was previously passing:
https://travis-ci.org/travis-ci/travis-cookbooks/jobs/249975917

However after rebasing it's now failing:
https://travis-ci.org/travis-ci/travis-cookbooks/jobs/250605484

Comparing the two I see the RuboCop version changed from 0.47.1 to 0.49.1, and so presumably the failures seen are just new offence types or defaults added in the new version:
https://github.com/bbatsov/rubocop/releases

This repo doesn't have a Gemfile, so I'm presuming the Gems come in from the underlying image? If so, I'm wondering if this is a side-effect of travis-ci/packer-templates#454?

**Comment by meatballhat** [comment]
The rubocop situation is definitely a bit confusing.  We don't have a Gemfile because we instead use the versions that come with ChefDK.  Running rubocop locally _without_ explicitly using the ChefDK version will likely result in a version bump like this, unless of course the latest ChefDK now uses 0.49.1... in which case we need to `rubocop -a --auto-gen-config`.

**Comment by edmorley** [comment]
Ah right that makes more sense. The failures I was seeing were in the Travis run, so using the version that comes with ChefDK.

Whilst it wouldn't be apparent from their changelog (since it's missing recent entries, for which I've filed chef/chef-dk#1315), they've recently bumped the RuboCop version:
chef/chef-dk#1272

**Comment by meatballhat** [comment]
Fixed via #865 :tada:
